// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sso-common/sso-common.proto

package sso_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus struct {
	Errors               []*ResponseStatus_Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8776310bb7bdb9, []int{0}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetErrors() []*ResponseStatus_Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type ResponseStatus_Error struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStatus_Error) Reset()         { *m = ResponseStatus_Error{} }
func (m *ResponseStatus_Error) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus_Error) ProtoMessage()    {}
func (*ResponseStatus_Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc8776310bb7bdb9, []int{0, 0}
}

func (m *ResponseStatus_Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus_Error.Unmarshal(m, b)
}
func (m *ResponseStatus_Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus_Error.Marshal(b, m, deterministic)
}
func (m *ResponseStatus_Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus_Error.Merge(m, src)
}
func (m *ResponseStatus_Error) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus_Error.Size(m)
}
func (m *ResponseStatus_Error) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus_Error.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus_Error proto.InternalMessageInfo

func (m *ResponseStatus_Error) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *ResponseStatus_Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ResponseStatus)(nil), "sso.common.ResponseStatus")
	proto.RegisterType((*ResponseStatus_Error)(nil), "sso.common.ResponseStatus.Error")
}

func init() { proto.RegisterFile("sso-common/sso-common.proto", fileDescriptor_cc8776310bb7bdb9) }

var fileDescriptor_cc8776310bb7bdb9 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcd, 0xaa, 0xc2, 0x30,
	0x10, 0x46, 0xc9, 0xfd, 0xe9, 0xe5, 0x8e, 0xe0, 0x22, 0xab, 0xa0, 0x9b, 0xe2, 0xaa, 0x9b, 0x26,
	0xa2, 0x08, 0xae, 0x05, 0x5f, 0xa0, 0xee, 0xdc, 0xa5, 0x1a, 0x62, 0xb1, 0xe9, 0x84, 0x4c, 0xfa,
	0x00, 0xbe, 0xb9, 0x34, 0x2a, 0xd5, 0xdd, 0x37, 0x87, 0x03, 0xc3, 0x81, 0x39, 0x11, 0x96, 0x27,
	0x74, 0x0e, 0x3b, 0x35, 0x4e, 0xe9, 0x03, 0x46, 0xe4, 0x40, 0x84, 0xf2, 0x41, 0x16, 0x37, 0x06,
	0xd3, 0xca, 0x90, 0xc7, 0x8e, 0xcc, 0x21, 0xea, 0xd8, 0x13, 0xdf, 0x42, 0x66, 0x42, 0xc0, 0x40,
	0x82, 0xe5, 0xdf, 0xc5, 0x64, 0x95, 0xcb, 0xd1, 0x97, 0x9f, 0xae, 0xdc, 0x0f, 0x62, 0xf5, 0xf4,
	0x67, 0x1b, 0xf8, 0x4d, 0x80, 0x73, 0xf8, 0xa1, 0xb6, 0xb7, 0x82, 0xe5, 0xac, 0xf8, 0xaf, 0xd2,
	0xe6, 0x02, 0xfe, 0x9c, 0x21, 0xd2, 0xd6, 0x88, 0xaf, 0x84, 0x5f, 0xe7, 0x6e, 0x79, 0x94, 0xb6,
	0x89, 0x97, 0xbe, 0x1e, 0x9e, 0x28, 0xab, 0x9d, 0x46, 0x4f, 0xca, 0x61, 0x87, 0x25, 0x11, 0x2a,
	0x7f, 0xb5, 0xaa, 0x39, 0xb7, 0x6f, 0x1d, 0x75, 0x96, 0x42, 0xd6, 0xf7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x84, 0xb5, 0x3b, 0xb3, 0xe7, 0x00, 0x00, 0x00,
}
