// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sso-manager/sso-manager.proto

package sso_manager

import (
	context "context"
	fmt "fmt"
	sso_common "github.com/gamaops/mono-sso/pkg/idl/sso-common"
	sso_service "github.com/gamaops/mono-sso/pkg/idl/sso-service"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientType int32

const (
	ClientType_PUBLIC       ClientType = 0
	ClientType_CONFIDENTIAL ClientType = 1
)

var ClientType_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}

var ClientType_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ClientType) String() string {
	return proto.EnumName(ClientType_name, int32(x))
}

func (ClientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{0}
}

type UpsertClientRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClientId             string                     `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Type                 ClientType                 `protobuf:"varint,3,opt,name=type,proto3,enum=sso.manager.ClientType" json:"type,omitempty"`
	RedirectUris         []string                   `protobuf:"bytes,4,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	Name                 string                     `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertClientRequest) Reset()         { *m = UpsertClientRequest{} }
func (m *UpsertClientRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertClientRequest) ProtoMessage()    {}
func (*UpsertClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{0}
}

func (m *UpsertClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertClientRequest.Unmarshal(m, b)
}
func (m *UpsertClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertClientRequest.Marshal(b, m, deterministic)
}
func (m *UpsertClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertClientRequest.Merge(m, src)
}
func (m *UpsertClientRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertClientRequest.Size(m)
}
func (m *UpsertClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertClientRequest proto.InternalMessageInfo

func (m *UpsertClientRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UpsertClientRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *UpsertClientRequest) GetType() ClientType {
	if m != nil {
		return m.Type
	}
	return ClientType_PUBLIC
}

func (m *UpsertClientRequest) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *UpsertClientRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpsertClientResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClientId             string                     `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string                     `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertClientResponse) Reset()         { *m = UpsertClientResponse{} }
func (m *UpsertClientResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertClientResponse) ProtoMessage()    {}
func (*UpsertClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{1}
}

func (m *UpsertClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertClientResponse.Unmarshal(m, b)
}
func (m *UpsertClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertClientResponse.Marshal(b, m, deterministic)
}
func (m *UpsertClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertClientResponse.Merge(m, src)
}
func (m *UpsertClientResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertClientResponse.Size(m)
}
func (m *UpsertClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertClientResponse proto.InternalMessageInfo

func (m *UpsertClientResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpsertClientResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *UpsertClientResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type DeleteClientRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClientId             string                     `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteClientRequest) Reset()         { *m = DeleteClientRequest{} }
func (m *DeleteClientRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClientRequest) ProtoMessage()    {}
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{2}
}

func (m *DeleteClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientRequest.Unmarshal(m, b)
}
func (m *DeleteClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientRequest.Merge(m, src)
}
func (m *DeleteClientRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClientRequest.Size(m)
}
func (m *DeleteClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientRequest proto.InternalMessageInfo

func (m *DeleteClientRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *DeleteClientRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type DeleteClientResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteClientResponse) Reset()         { *m = DeleteClientResponse{} }
func (m *DeleteClientResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResponse) ProtoMessage()    {}
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{3}
}

func (m *DeleteClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResponse.Unmarshal(m, b)
}
func (m *DeleteClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResponse.Marshal(b, m, deterministic)
}
func (m *DeleteClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResponse.Merge(m, src)
}
func (m *DeleteClientResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResponse.Size(m)
}
func (m *DeleteClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResponse proto.InternalMessageInfo

func (m *DeleteClientResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type UpsertScopeRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClientId             string                     `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope                string                     `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Description          string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertScopeRequest) Reset()         { *m = UpsertScopeRequest{} }
func (m *UpsertScopeRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertScopeRequest) ProtoMessage()    {}
func (*UpsertScopeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{4}
}

func (m *UpsertScopeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertScopeRequest.Unmarshal(m, b)
}
func (m *UpsertScopeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertScopeRequest.Marshal(b, m, deterministic)
}
func (m *UpsertScopeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertScopeRequest.Merge(m, src)
}
func (m *UpsertScopeRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertScopeRequest.Size(m)
}
func (m *UpsertScopeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertScopeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertScopeRequest proto.InternalMessageInfo

func (m *UpsertScopeRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UpsertScopeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *UpsertScopeRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *UpsertScopeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpsertScopeResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertScopeResponse) Reset()         { *m = UpsertScopeResponse{} }
func (m *UpsertScopeResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertScopeResponse) ProtoMessage()    {}
func (*UpsertScopeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{5}
}

func (m *UpsertScopeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertScopeResponse.Unmarshal(m, b)
}
func (m *UpsertScopeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertScopeResponse.Marshal(b, m, deterministic)
}
func (m *UpsertScopeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertScopeResponse.Merge(m, src)
}
func (m *UpsertScopeResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertScopeResponse.Size(m)
}
func (m *UpsertScopeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertScopeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertScopeResponse proto.InternalMessageInfo

func (m *UpsertScopeResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeleteScopeRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ClientId             string                     `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope                string                     `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteScopeRequest) Reset()         { *m = DeleteScopeRequest{} }
func (m *DeleteScopeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteScopeRequest) ProtoMessage()    {}
func (*DeleteScopeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{6}
}

func (m *DeleteScopeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteScopeRequest.Unmarshal(m, b)
}
func (m *DeleteScopeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteScopeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteScopeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScopeRequest.Merge(m, src)
}
func (m *DeleteScopeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteScopeRequest.Size(m)
}
func (m *DeleteScopeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScopeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScopeRequest proto.InternalMessageInfo

func (m *DeleteScopeRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *DeleteScopeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *DeleteScopeRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type DeleteScopeResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteScopeResponse) Reset()         { *m = DeleteScopeResponse{} }
func (m *DeleteScopeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteScopeResponse) ProtoMessage()    {}
func (*DeleteScopeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{7}
}

func (m *DeleteScopeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteScopeResponse.Unmarshal(m, b)
}
func (m *DeleteScopeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteScopeResponse.Marshal(b, m, deterministic)
}
func (m *DeleteScopeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScopeResponse.Merge(m, src)
}
func (m *DeleteScopeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteScopeResponse.Size(m)
}
func (m *DeleteScopeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScopeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScopeResponse proto.InternalMessageInfo

func (m *DeleteScopeResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type UpsertTenantRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	TenantId             string                     `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name                 string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertTenantRequest) Reset()         { *m = UpsertTenantRequest{} }
func (m *UpsertTenantRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertTenantRequest) ProtoMessage()    {}
func (*UpsertTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{8}
}

func (m *UpsertTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertTenantRequest.Unmarshal(m, b)
}
func (m *UpsertTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertTenantRequest.Marshal(b, m, deterministic)
}
func (m *UpsertTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertTenantRequest.Merge(m, src)
}
func (m *UpsertTenantRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertTenantRequest.Size(m)
}
func (m *UpsertTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertTenantRequest proto.InternalMessageInfo

func (m *UpsertTenantRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UpsertTenantRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *UpsertTenantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpsertTenantResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TenantId             string                     `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertTenantResponse) Reset()         { *m = UpsertTenantResponse{} }
func (m *UpsertTenantResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertTenantResponse) ProtoMessage()    {}
func (*UpsertTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{9}
}

func (m *UpsertTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertTenantResponse.Unmarshal(m, b)
}
func (m *UpsertTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertTenantResponse.Marshal(b, m, deterministic)
}
func (m *UpsertTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertTenantResponse.Merge(m, src)
}
func (m *UpsertTenantResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertTenantResponse.Size(m)
}
func (m *UpsertTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertTenantResponse proto.InternalMessageInfo

func (m *UpsertTenantResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpsertTenantResponse) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type DeleteTenantRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	TenantId             string                     `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteTenantRequest) Reset()         { *m = DeleteTenantRequest{} }
func (m *DeleteTenantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTenantRequest) ProtoMessage()    {}
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{10}
}

func (m *DeleteTenantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTenantRequest.Unmarshal(m, b)
}
func (m *DeleteTenantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTenantRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTenantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTenantRequest.Merge(m, src)
}
func (m *DeleteTenantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTenantRequest.Size(m)
}
func (m *DeleteTenantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTenantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTenantRequest proto.InternalMessageInfo

func (m *DeleteTenantRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *DeleteTenantRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type DeleteTenantResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteTenantResponse) Reset()         { *m = DeleteTenantResponse{} }
func (m *DeleteTenantResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTenantResponse) ProtoMessage()    {}
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{11}
}

func (m *DeleteTenantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTenantResponse.Unmarshal(m, b)
}
func (m *DeleteTenantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTenantResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTenantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTenantResponse.Merge(m, src)
}
func (m *DeleteTenantResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTenantResponse.Size(m)
}
func (m *DeleteTenantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTenantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTenantResponse proto.InternalMessageInfo

func (m *DeleteTenantResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type UpsertAccountRequest struct {
	Session              *sso_common.RequestSession   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	AccountId            string                       `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ActivationMethod     sso_service.ActivationMethod `protobuf:"varint,3,opt,name=activation_method,json=activationMethod,proto3,enum=sso.service.ActivationMethod" json:"activation_method,omitempty"`
	Password             string                       `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string                       `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Identifiers          []string                     `protobuf:"bytes,6,rep,name=identifiers,proto3" json:"identifiers,omitempty"`
	TenantIds            []string                     `protobuf:"bytes,7,rep,name=tenant_ids,json=tenantIds,proto3" json:"tenant_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *UpsertAccountRequest) Reset()         { *m = UpsertAccountRequest{} }
func (m *UpsertAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpsertAccountRequest) ProtoMessage()    {}
func (*UpsertAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{12}
}

func (m *UpsertAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertAccountRequest.Unmarshal(m, b)
}
func (m *UpsertAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpsertAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertAccountRequest.Merge(m, src)
}
func (m *UpsertAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpsertAccountRequest.Size(m)
}
func (m *UpsertAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertAccountRequest proto.InternalMessageInfo

func (m *UpsertAccountRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *UpsertAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpsertAccountRequest) GetActivationMethod() sso_service.ActivationMethod {
	if m != nil {
		return m.ActivationMethod
	}
	return sso_service.ActivationMethod_NONE
}

func (m *UpsertAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpsertAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpsertAccountRequest) GetIdentifiers() []string {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *UpsertAccountRequest) GetTenantIds() []string {
	if m != nil {
		return m.TenantIds
	}
	return nil
}

type UpsertAccountResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UpsertAccountResponse) Reset()         { *m = UpsertAccountResponse{} }
func (m *UpsertAccountResponse) String() string { return proto.CompactTextString(m) }
func (*UpsertAccountResponse) ProtoMessage()    {}
func (*UpsertAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{13}
}

func (m *UpsertAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpsertAccountResponse.Unmarshal(m, b)
}
func (m *UpsertAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpsertAccountResponse.Marshal(b, m, deterministic)
}
func (m *UpsertAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpsertAccountResponse.Merge(m, src)
}
func (m *UpsertAccountResponse) XXX_Size() int {
	return xxx_messageInfo_UpsertAccountResponse.Size(m)
}
func (m *UpsertAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpsertAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpsertAccountResponse proto.InternalMessageInfo

func (m *UpsertAccountResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeleteAccountRequest struct {
	Session              *sso_common.RequestSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	AccountId            string                     `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{14}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetSession() *sso_common.RequestSession {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *DeleteAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DeleteAccountResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{15}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func (m *DeleteAccountResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("sso.manager.ClientType", ClientType_name, ClientType_value)
	proto.RegisterType((*UpsertClientRequest)(nil), "sso.manager.UpsertClientRequest")
	proto.RegisterType((*UpsertClientResponse)(nil), "sso.manager.UpsertClientResponse")
	proto.RegisterType((*DeleteClientRequest)(nil), "sso.manager.DeleteClientRequest")
	proto.RegisterType((*DeleteClientResponse)(nil), "sso.manager.DeleteClientResponse")
	proto.RegisterType((*UpsertScopeRequest)(nil), "sso.manager.UpsertScopeRequest")
	proto.RegisterType((*UpsertScopeResponse)(nil), "sso.manager.UpsertScopeResponse")
	proto.RegisterType((*DeleteScopeRequest)(nil), "sso.manager.DeleteScopeRequest")
	proto.RegisterType((*DeleteScopeResponse)(nil), "sso.manager.DeleteScopeResponse")
	proto.RegisterType((*UpsertTenantRequest)(nil), "sso.manager.UpsertTenantRequest")
	proto.RegisterType((*UpsertTenantResponse)(nil), "sso.manager.UpsertTenantResponse")
	proto.RegisterType((*DeleteTenantRequest)(nil), "sso.manager.DeleteTenantRequest")
	proto.RegisterType((*DeleteTenantResponse)(nil), "sso.manager.DeleteTenantResponse")
	proto.RegisterType((*UpsertAccountRequest)(nil), "sso.manager.UpsertAccountRequest")
	proto.RegisterType((*UpsertAccountResponse)(nil), "sso.manager.UpsertAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "sso.manager.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "sso.manager.DeleteAccountResponse")
}

func init() { proto.RegisterFile("sso-manager/sso-manager.proto", fileDescriptor_7c09c63b2fb56424) }

var fileDescriptor_7c09c63b2fb56424 = []byte{
	// 758 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x51, 0x4e, 0xdb, 0x4a,
	0x14, 0x7d, 0x86, 0x10, 0xc8, 0x4d, 0x82, 0xc2, 0xc0, 0xd3, 0x8b, 0x8c, 0xd0, 0xf3, 0x33, 0x3f,
	0x11, 0x4f, 0xc4, 0x6a, 0xda, 0x0d, 0x40, 0x68, 0x25, 0x53, 0xa0, 0xd4, 0x01, 0x3e, 0xfa, 0x83,
	0x8c, 0x3d, 0x0d, 0x23, 0xb0, 0xc7, 0xf5, 0x4c, 0xa8, 0x90, 0xda, 0x1d, 0x74, 0x0f, 0xfd, 0xed,
	0x26, 0x2a, 0x75, 0x05, 0x5d, 0x42, 0xd7, 0x52, 0x79, 0x3c, 0x4e, 0x6c, 0x77, 0x88, 0x2a, 0x52,
	0xda, 0xbf, 0xc9, 0x9d, 0xa3, 0x7b, 0xef, 0x39, 0x99, 0x73, 0xaf, 0x61, 0x83, 0x31, 0xba, 0x1d,
	0xb8, 0xa1, 0x3b, 0xc4, 0xb1, 0x95, 0x3b, 0x77, 0xa3, 0x98, 0x72, 0x8a, 0xea, 0x8c, 0xd1, 0xae,
	0x0c, 0xe9, 0xeb, 0xc9, 0xbd, 0x47, 0x83, 0x80, 0x86, 0xd6, 0xe4, 0x98, 0x22, 0x75, 0x91, 0x88,
	0xe1, 0xf8, 0x86, 0x78, 0xd8, 0xca, 0x9d, 0xd3, 0x6b, 0xf3, 0xab, 0x06, 0xab, 0xa7, 0x11, 0xc3,
	0x31, 0xef, 0x5f, 0x13, 0x1c, 0x72, 0x07, 0xbf, 0x19, 0x61, 0xc6, 0xd1, 0x13, 0x58, 0x64, 0x98,
	0x31, 0x42, 0xc3, 0xb6, 0x66, 0x68, 0x9d, 0x7a, 0x4f, 0xef, 0x26, 0x25, 0x65, 0x6a, 0x89, 0x1a,
	0xa4, 0x08, 0x27, 0x83, 0xa2, 0x75, 0xa8, 0x79, 0x22, 0xcd, 0x39, 0xf1, 0xdb, 0x73, 0x86, 0xd6,
	0xa9, 0x39, 0x4b, 0x69, 0xc0, 0xf6, 0xd1, 0xff, 0x50, 0xe1, 0xb7, 0x11, 0x6e, 0xcf, 0x1b, 0x5a,
	0x67, 0xb9, 0xf7, 0x4f, 0x37, 0x47, 0xa1, 0x9b, 0x16, 0x3f, 0xb9, 0x8d, 0xb0, 0x23, 0x40, 0x68,
	0x13, 0x9a, 0x31, 0xf6, 0x49, 0x8c, 0x3d, 0x7e, 0x3e, 0x8a, 0x09, 0x6b, 0x57, 0x8c, 0xf9, 0x4e,
	0xcd, 0x69, 0x64, 0xc1, 0xd3, 0x98, 0x30, 0x84, 0xa0, 0x12, 0xba, 0x01, 0x6e, 0x2f, 0x88, 0x4a,
	0xe2, 0x6c, 0x7e, 0xd0, 0x60, 0xad, 0x48, 0x88, 0x45, 0x34, 0x64, 0x18, 0xf5, 0xa0, 0xca, 0xb8,
	0xcb, 0x47, 0x4c, 0x4d, 0x28, 0x45, 0x0d, 0x04, 0xc2, 0x91, 0xc8, 0xe9, 0x7c, 0x36, 0xa1, 0x29,
	0x2f, 0x19, 0xf6, 0x62, 0xcc, 0x05, 0xb1, 0x9a, 0xd3, 0x48, 0x83, 0x03, 0x11, 0x33, 0x2f, 0x61,
	0x75, 0x0f, 0x5f, 0x63, 0x8e, 0x1f, 0x5a, 0x5e, 0x73, 0x1f, 0xd6, 0x8a, 0x95, 0xee, 0xcf, 0xdb,
	0xfc, 0xa8, 0x01, 0x4a, 0x45, 0x1c, 0x78, 0x34, 0xc2, 0x0f, 0xf8, 0x28, 0xd6, 0x60, 0x81, 0x25,
	0x25, 0xa4, 0x78, 0xe9, 0x0f, 0x64, 0x40, 0xdd, 0xc7, 0xcc, 0x8b, 0x49, 0xc4, 0x93, 0x62, 0x15,
	0x71, 0x97, 0x0f, 0x99, 0x76, 0xf6, 0x6c, 0x65, 0x83, 0x33, 0x90, 0x7d, 0x0f, 0x28, 0x15, 0xee,
	0x8f, 0x70, 0x4d, 0x98, 0x14, 0xca, 0xcf, 0xc0, 0xe4, 0x5d, 0x26, 0xca, 0x09, 0x0e, 0xdd, 0x5f,
	0xf0, 0xd8, 0xb8, 0x48, 0x93, 0xa3, 0x92, 0x06, 0x6c, 0x7f, 0xec, 0xbc, 0xf9, 0x9c, 0xf3, 0x86,
	0x99, 0xf1, 0xb2, 0xea, 0xb3, 0x19, 0xef, 0xce, 0xe2, 0x13, 0x4f, 0x3d, 0x34, 0xcd, 0x89, 0xa7,
	0x66, 0xa7, 0x64, 0x7e, 0x9a, 0xcb, 0xf4, 0xd9, 0xf1, 0x3c, 0x3a, 0x9a, 0xb5, 0xef, 0x0d, 0x00,
	0x37, 0xcd, 0x33, 0x69, 0xbc, 0x26, 0x23, 0xb6, 0x8f, 0xf6, 0x61, 0xc5, 0xf5, 0x38, 0xb9, 0x71,
	0x13, 0xb7, 0x9c, 0x07, 0x98, 0x5f, 0x52, 0x5f, 0x4e, 0xde, 0x0d, 0x91, 0x3e, 0x5b, 0x03, 0x3b,
	0x63, 0xd4, 0xa1, 0x00, 0x39, 0x2d, 0xb7, 0x14, 0x41, 0x3a, 0x2c, 0x45, 0x2e, 0x63, 0x6f, 0x69,
	0xec, 0x4b, 0x2b, 0x8e, 0x7f, 0xab, 0x46, 0x70, 0xe2, 0x5e, 0xe2, 0xe3, 0x90, 0x93, 0xd7, 0x04,
	0xc7, 0xac, 0x5d, 0x15, 0x93, 0x3b, 0x1f, 0x4a, 0x9a, 0x1f, 0x8b, 0xce, 0xda, 0x8b, 0x02, 0x50,
	0xcb, 0x54, 0x67, 0xe6, 0x73, 0xf8, 0xbb, 0xa4, 0xd4, 0x0c, 0xba, 0x5f, 0x65, 0xff, 0xe1, 0x6f,
	0x90, 0x3d, 0xe9, 0xbc, 0x54, 0xec, 0xfe, 0x9d, 0x6f, 0x6d, 0x01, 0x4c, 0xf6, 0x22, 0x02, 0xa8,
	0x1e, 0x9f, 0xee, 0x1e, 0xd8, 0xfd, 0xd6, 0x5f, 0xa8, 0x05, 0x8d, 0xfe, 0x8b, 0xa3, 0x67, 0xf6,
	0xde, 0xd3, 0xa3, 0x13, 0x7b, 0xe7, 0xa0, 0xa5, 0xf5, 0xbe, 0xcd, 0x41, 0xb3, 0x2f, 0x17, 0x8f,
	0xf8, 0x63, 0xd1, 0x00, 0x1a, 0xf9, 0x3d, 0x88, 0x8c, 0xc2, 0xc2, 0x55, 0xec, 0x7c, 0xfd, 0xbf,
	0x29, 0x08, 0x49, 0x63, 0x00, 0x8d, 0xfc, 0x92, 0x29, 0x25, 0x55, 0x6c, 0xba, 0x52, 0x52, 0xe5,
	0x86, 0x3a, 0x86, 0x7a, 0x6e, 0x96, 0xa3, 0x7f, 0x15, 0x6d, 0xe4, 0x47, 0xb3, 0x6e, 0xdc, 0x0d,
	0x90, 0x19, 0x5f, 0x42, 0x3d, 0x37, 0x53, 0x4b, 0x19, 0x7f, 0x1c, 0xf6, 0x3f, 0xd1, 0x64, 0xef,
	0xb3, 0x06, 0x2b, 0x87, 0x02, 0x10, 0xa8, 0x44, 0x4e, 0x07, 0x84, 0x52, 0xe4, 0xc2, 0x94, 0x52,
	0x8a, 0x5c, 0x9a, 0x2e, 0x63, 0x91, 0x95, 0x49, 0x15, 0xa3, 0x4f, 0xd9, 0x7f, 0x31, 0x69, 0xef,
	0x8b, 0x06, 0xcb, 0xf2, 0x51, 0x66, 0xcd, 0x9f, 0x41, 0xb3, 0x60, 0x33, 0xa4, 0xea, 0xad, 0xe8,
	0x1a, 0xdd, 0x9c, 0x06, 0x91, 0xfd, 0x9f, 0x41, 0xb3, 0x60, 0x02, 0xa4, 0x6a, 0x6f, 0x6a, 0x5e,
	0xa5, 0x87, 0x76, 0x1f, 0xbd, 0xb2, 0x86, 0x84, 0x5f, 0x8e, 0x2e, 0x12, 0xdf, 0x58, 0x43, 0x37,
	0x70, 0x69, 0xc4, 0xac, 0x80, 0x86, 0x74, 0x9b, 0x31, 0x6a, 0x45, 0x57, 0x43, 0x8b, 0xf8, 0xd7,
	0xf9, 0xaf, 0xe5, 0x8b, 0xaa, 0xf8, 0xca, 0x7d, 0xfc, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x45, 0x1a,
	0x1e, 0x22, 0x4f, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	UpsertClient(ctx context.Context, in *UpsertClientRequest, opts ...grpc.CallOption) (*UpsertClientResponse, error)
	DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error)
	UpsertScope(ctx context.Context, in *UpsertScopeRequest, opts ...grpc.CallOption) (*UpsertScopeResponse, error)
	DeleteScope(ctx context.Context, in *DeleteScopeRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error)
}

type clientServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientServiceClient(cc *grpc.ClientConn) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) UpsertClient(ctx context.Context, in *UpsertClientRequest, opts ...grpc.CallOption) (*UpsertClientResponse, error) {
	out := new(UpsertClientResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ClientService/UpsertClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) DeleteClient(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error) {
	out := new(DeleteClientResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ClientService/DeleteClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) UpsertScope(ctx context.Context, in *UpsertScopeRequest, opts ...grpc.CallOption) (*UpsertScopeResponse, error) {
	out := new(UpsertScopeResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ClientService/UpsertScope", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) DeleteScope(ctx context.Context, in *DeleteScopeRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error) {
	out := new(DeleteClientResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ClientService/DeleteScope", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	UpsertClient(context.Context, *UpsertClientRequest) (*UpsertClientResponse, error)
	DeleteClient(context.Context, *DeleteClientRequest) (*DeleteClientResponse, error)
	UpsertScope(context.Context, *UpsertScopeRequest) (*UpsertScopeResponse, error)
	DeleteScope(context.Context, *DeleteScopeRequest) (*DeleteClientResponse, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) UpsertClient(ctx context.Context, req *UpsertClientRequest) (*UpsertClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertClient not implemented")
}
func (*UnimplementedClientServiceServer) DeleteClient(ctx context.Context, req *DeleteClientRequest) (*DeleteClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteClient not implemented")
}
func (*UnimplementedClientServiceServer) UpsertScope(ctx context.Context, req *UpsertScopeRequest) (*UpsertScopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertScope not implemented")
}
func (*UnimplementedClientServiceServer) DeleteScope(ctx context.Context, req *DeleteScopeRequest) (*DeleteClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteScope not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_UpsertClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpsertClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ClientService/UpsertClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpsertClient(ctx, req.(*UpsertClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_DeleteClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).DeleteClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ClientService/DeleteClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).DeleteClient(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_UpsertScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).UpsertScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ClientService/UpsertScope",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).UpsertScope(ctx, req.(*UpsertScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_DeleteScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).DeleteScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ClientService/DeleteScope",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).DeleteScope(ctx, req.(*DeleteScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.manager.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertClient",
			Handler:    _ClientService_UpsertClient_Handler,
		},
		{
			MethodName: "DeleteClient",
			Handler:    _ClientService_DeleteClient_Handler,
		},
		{
			MethodName: "UpsertScope",
			Handler:    _ClientService_UpsertScope_Handler,
		},
		{
			MethodName: "DeleteScope",
			Handler:    _ClientService_DeleteScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-manager/sso-manager.proto",
}

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagementServiceClient interface {
	UpsertTenant(ctx context.Context, in *UpsertTenantRequest, opts ...grpc.CallOption) (*UpsertTenantResponse, error)
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
}

type managementServiceClient struct {
	cc *grpc.ClientConn
}

func NewManagementServiceClient(cc *grpc.ClientConn) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) UpsertTenant(ctx context.Context, in *UpsertTenantRequest, opts ...grpc.CallOption) (*UpsertTenantResponse, error) {
	out := new(UpsertTenantResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ManagementService/UpsertTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ManagementService/DeleteTenant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
type ManagementServiceServer interface {
	UpsertTenant(context.Context, *UpsertTenantRequest) (*UpsertTenantResponse, error)
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
}

// UnimplementedManagementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagementServiceServer struct {
}

func (*UnimplementedManagementServiceServer) UpsertTenant(ctx context.Context, req *UpsertTenantRequest) (*UpsertTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertTenant not implemented")
}
func (*UnimplementedManagementServiceServer) DeleteTenant(ctx context.Context, req *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenant not implemented")
}

func RegisterManagementServiceServer(s *grpc.Server, srv ManagementServiceServer) {
	s.RegisterService(&_ManagementService_serviceDesc, srv)
}

func _ManagementService_UpsertTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpsertTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ManagementService/UpsertTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpsertTenant(ctx, req.(*UpsertTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ManagementService/DeleteTenant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.manager.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertTenant",
			Handler:    _ManagementService_UpsertTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _ManagementService_DeleteTenant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-manager/sso-manager.proto",
}

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	UpsertAccount(ctx context.Context, in *UpsertAccountRequest, opts ...grpc.CallOption) (*UpsertAccountResponse, error)
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) UpsertAccount(ctx context.Context, in *UpsertAccountRequest, opts ...grpc.CallOption) (*UpsertAccountResponse, error) {
	out := new(UpsertAccountResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.AccountService/UpsertAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.AccountService/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	UpsertAccount(context.Context, *UpsertAccountRequest) (*UpsertAccountResponse, error)
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) UpsertAccount(ctx context.Context, req *UpsertAccountRequest) (*UpsertAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertAccount not implemented")
}
func (*UnimplementedAccountServiceServer) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_UpsertAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpsertAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.AccountService/UpsertAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpsertAccount(ctx, req.(*UpsertAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.AccountService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.manager.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertAccount",
			Handler:    _AccountService_UpsertAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _AccountService_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-manager/sso-manager.proto",
}
