// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sso-manager/sso-manager.proto

package sso_manager

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	sso_common "sso-common"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientType int32

const (
	ClientType_PUBLIC       ClientType = 0
	ClientType_CONFIDENTIAL ClientType = 1
)

var ClientType_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}

var ClientType_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ClientType) String() string {
	return proto.EnumName(ClientType_name, int32(x))
}

func (ClientType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{0}
}

type CreateClientRequest struct {
	Type                 ClientType `protobuf:"varint,1,opt,name=type,proto3,enum=sso.manager.ClientType" json:"type,omitempty"`
	RedirectUris         []string   `protobuf:"bytes,2,rep,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{0}
}

func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(m, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetType() ClientType {
	if m != nil {
		return m.Type
	}
	return ClientType_PUBLIC
}

func (m *CreateClientRequest) GetRedirectUris() []string {
	if m != nil {
		return m.RedirectUris
	}
	return nil
}

func (m *CreateClientRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateClientResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ClientId             string                     `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret         string                     `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateClientResponse) Reset()         { *m = CreateClientResponse{} }
func (m *CreateClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClientResponse) ProtoMessage()    {}
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{1}
}

func (m *CreateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResponse.Unmarshal(m, b)
}
func (m *CreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResponse.Marshal(b, m, deterministic)
}
func (m *CreateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResponse.Merge(m, src)
}
func (m *CreateClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClientResponse.Size(m)
}
func (m *CreateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResponse proto.InternalMessageInfo

func (m *CreateClientResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateClientResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CreateClientResponse) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

type CreateScopeRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope                string   `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateScopeRequest) Reset()         { *m = CreateScopeRequest{} }
func (m *CreateScopeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateScopeRequest) ProtoMessage()    {}
func (*CreateScopeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{2}
}

func (m *CreateScopeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScopeRequest.Unmarshal(m, b)
}
func (m *CreateScopeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScopeRequest.Marshal(b, m, deterministic)
}
func (m *CreateScopeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScopeRequest.Merge(m, src)
}
func (m *CreateScopeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateScopeRequest.Size(m)
}
func (m *CreateScopeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScopeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScopeRequest proto.InternalMessageInfo

func (m *CreateScopeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CreateScopeRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *CreateScopeRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateScopeResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ScopeId              string                     `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CreateScopeResponse) Reset()         { *m = CreateScopeResponse{} }
func (m *CreateScopeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateScopeResponse) ProtoMessage()    {}
func (*CreateScopeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c09c63b2fb56424, []int{3}
}

func (m *CreateScopeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateScopeResponse.Unmarshal(m, b)
}
func (m *CreateScopeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateScopeResponse.Marshal(b, m, deterministic)
}
func (m *CreateScopeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateScopeResponse.Merge(m, src)
}
func (m *CreateScopeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateScopeResponse.Size(m)
}
func (m *CreateScopeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateScopeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateScopeResponse proto.InternalMessageInfo

func (m *CreateScopeResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CreateScopeResponse) GetScopeId() string {
	if m != nil {
		return m.ScopeId
	}
	return ""
}

func init() {
	proto.RegisterEnum("sso.manager.ClientType", ClientType_name, ClientType_value)
	proto.RegisterType((*CreateClientRequest)(nil), "sso.manager.CreateClientRequest")
	proto.RegisterType((*CreateClientResponse)(nil), "sso.manager.CreateClientResponse")
	proto.RegisterType((*CreateScopeRequest)(nil), "sso.manager.CreateScopeRequest")
	proto.RegisterType((*CreateScopeResponse)(nil), "sso.manager.CreateScopeResponse")
}

func init() { proto.RegisterFile("sso-manager/sso-manager.proto", fileDescriptor_7c09c63b2fb56424) }

var fileDescriptor_7c09c63b2fb56424 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xed, 0x8a, 0xda, 0x40,
	0x14, 0x6d, 0xd4, 0x5a, 0xbd, 0x89, 0x45, 0xa6, 0x42, 0xd3, 0x48, 0x69, 0x9a, 0xfe, 0x11, 0x4b,
	0x23, 0xa4, 0x4f, 0xd0, 0xa6, 0x2d, 0x04, 0xc4, 0x4a, 0xa2, 0xbf, 0x25, 0x4d, 0x2e, 0x65, 0x60,
	0x93, 0xc9, 0xce, 0x8c, 0x0b, 0xb2, 0xaf, 0xb0, 0xcf, 0xb3, 0xcf, 0xb7, 0x38, 0x99, 0x60, 0xdc,
	0xaf, 0x3f, 0xfb, 0xef, 0xce, 0x99, 0x33, 0xe7, 0x9c, 0x7b, 0xe7, 0xc2, 0x47, 0x21, 0xd8, 0xb7,
	0x22, 0x2d, 0xd3, 0xff, 0xc8, 0x17, 0xad, 0xda, 0xaf, 0x38, 0x93, 0x8c, 0x98, 0x42, 0x30, 0x5f,
	0x43, 0xce, 0xf4, 0x78, 0x9f, 0xb1, 0xa2, 0x60, 0xe5, 0xe2, 0x54, 0xd6, 0x4c, 0xef, 0x1a, 0xde,
	0x85, 0x1c, 0x53, 0x89, 0xe1, 0x05, 0xc5, 0x52, 0xc6, 0x78, 0xb9, 0x47, 0x21, 0xc9, 0x57, 0xe8,
	0xc9, 0x43, 0x85, 0xb6, 0xe1, 0x1a, 0xb3, 0xb7, 0xc1, 0x7b, 0xbf, 0xa5, 0xe7, 0xd7, 0xcc, 0xcd,
	0xa1, 0xc2, 0x58, 0x91, 0xc8, 0x17, 0x18, 0x71, 0xcc, 0x29, 0xc7, 0x4c, 0xee, 0xf6, 0x9c, 0x0a,
	0xbb, 0xe3, 0x76, 0x67, 0xc3, 0xd8, 0x6a, 0xc0, 0x2d, 0xa7, 0x82, 0x10, 0xe8, 0x95, 0x69, 0x81,
	0x76, 0xd7, 0x35, 0x66, 0xc3, 0x58, 0xd5, 0xde, 0x8d, 0x01, 0x93, 0x73, 0x77, 0x51, 0xb1, 0x52,
	0x20, 0x09, 0xa0, 0x2f, 0x64, 0x2a, 0xf7, 0x42, 0x05, 0x30, 0x03, 0x47, 0x05, 0xd0, 0xc1, 0x1b,
	0x56, 0xa2, 0x18, 0xb1, 0x66, 0x92, 0x29, 0x0c, 0x33, 0xa5, 0xb2, 0xa3, 0xb9, 0xdd, 0x51, 0x2e,
	0x83, 0x1a, 0x88, 0xf2, 0x63, 0x44, 0x7d, 0x29, 0x30, 0xe3, 0x28, 0x75, 0x0c, 0xab, 0x06, 0x13,
	0x85, 0x79, 0x14, 0x48, 0x9d, 0x26, 0xc9, 0x58, 0x85, 0xcd, 0x28, 0xce, 0x74, 0x8d, 0x7b, 0xba,
	0x13, 0x78, 0x2d, 0x8e, 0x64, 0x6d, 0x58, 0x1f, 0x88, 0x0b, 0x66, 0x8e, 0x22, 0xe3, 0xb4, 0x92,
	0x94, 0x95, 0xda, 0xab, 0x0d, 0x79, 0x79, 0x33, 0x76, 0x6d, 0xf5, 0x82, 0xbe, 0x3f, 0xc0, 0x40,
	0xb9, 0x9e, 0xda, 0x7e, 0xa3, 0xce, 0x51, 0x3e, 0x9f, 0x03, 0x9c, 0x3e, 0x8b, 0x00, 0xf4, 0xd7,
	0xdb, 0x9f, 0xcb, 0x28, 0x1c, 0xbf, 0x22, 0x63, 0xb0, 0xc2, 0xbf, 0xab, 0x3f, 0xd1, 0xaf, 0xdf,
	0xab, 0x4d, 0xf4, 0x63, 0x39, 0x36, 0x82, 0x5b, 0x03, 0x46, 0xa1, 0x9e, 0x06, 0xbf, 0xa2, 0x19,
	0x92, 0x04, 0xac, 0xf6, 0xe7, 0x10, 0xf7, 0x7c, 0x0b, 0x1e, 0x6e, 0x8d, 0xf3, 0xf9, 0x19, 0x86,
	0xee, 0x70, 0x0d, 0x66, 0xab, 0x71, 0xf2, 0xe9, 0x91, 0x17, 0xed, 0xe9, 0x3b, 0xee, 0xd3, 0x84,
	0x5a, 0xf1, 0x5f, 0x5f, 0x2d, 0xf2, 0xf7, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0x74, 0x69,
	0x1e, 0x13, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	CreateScope(ctx context.Context, in *CreateScopeRequest, opts ...grpc.CallOption) (*CreateScopeResponse, error)
}

type clientServiceClient struct {
	cc *grpc.ClientConn
}

func NewClientServiceClient(cc *grpc.ClientConn) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) CreateClient(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ClientService/CreateClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientServiceClient) CreateScope(ctx context.Context, in *CreateScopeRequest, opts ...grpc.CallOption) (*CreateScopeResponse, error) {
	out := new(CreateScopeResponse)
	err := c.cc.Invoke(ctx, "/sso.manager.ClientService/CreateScope", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	CreateClient(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	CreateScope(context.Context, *CreateScopeRequest) (*CreateScopeResponse, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) CreateClient(ctx context.Context, req *CreateClientRequest) (*CreateClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateClient not implemented")
}
func (*UnimplementedClientServiceServer) CreateScope(ctx context.Context, req *CreateScopeRequest) (*CreateScopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateScope not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_CreateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ClientService/CreateClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateClient(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientService_CreateScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).CreateScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.manager.ClientService/CreateScope",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).CreateScope(ctx, req.(*CreateScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.manager.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateClient",
			Handler:    _ClientService_CreateClient_Handler,
		},
		{
			MethodName: "CreateScope",
			Handler:    _ClientService_CreateScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-manager/sso-manager.proto",
}
