// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sso-service/sso-service.proto

package sso_service

import (
	context "context"
	fmt "fmt"
	sso_common "github.com/gamaops/mono-sso/pkg/idl/sso-common"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActivationMethod int32

const (
	ActivationMethod_NONE                 ActivationMethod = 0
	ActivationMethod_EMAIL                ActivationMethod = 1
	ActivationMethod_SMS                  ActivationMethod = 2
	ActivationMethod_GOOGLE_AUTHENTICATOR ActivationMethod = 3
	ActivationMethod_WEBHOOK              ActivationMethod = 4
	ActivationMethod_WHATSAPP             ActivationMethod = 5
)

var ActivationMethod_name = map[int32]string{
	0: "NONE",
	1: "EMAIL",
	2: "SMS",
	3: "GOOGLE_AUTHENTICATOR",
	4: "WEBHOOK",
	5: "WHATSAPP",
}

var ActivationMethod_value = map[string]int32{
	"NONE":                 0,
	"EMAIL":                1,
	"SMS":                  2,
	"GOOGLE_AUTHENTICATOR": 3,
	"WEBHOOK":              4,
	"WHATSAPP":             5,
}

func (x ActivationMethod) String() string {
	return proto.EnumName(ActivationMethod_name, int32(x))
}

func (ActivationMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{0}
}

type EventLevel int32

const (
	EventLevel_INFO    EventLevel = 0
	EventLevel_WARNING EventLevel = 1
)

var EventLevel_name = map[int32]string{
	0: "INFO",
	1: "WARNING",
}

var EventLevel_value = map[string]int32{
	"INFO":    0,
	"WARNING": 1,
}

func (x EventLevel) String() string {
	return proto.EnumName(EventLevel_name, int32(x))
}

func (EventLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{1}
}

type AccountProfile struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountProfile) Reset()         { *m = AccountProfile{} }
func (m *AccountProfile) String() string { return proto.CompactTextString(m) }
func (*AccountProfile) ProtoMessage()    {}
func (*AccountProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{0}
}

func (m *AccountProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountProfile.Unmarshal(m, b)
}
func (m *AccountProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountProfile.Marshal(b, m, deterministic)
}
func (m *AccountProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountProfile.Merge(m, src)
}
func (m *AccountProfile) XXX_Size() int {
	return xxx_messageInfo_AccountProfile.Size(m)
}
func (m *AccountProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountProfile.DiscardUnknown(m)
}

var xxx_messageInfo_AccountProfile proto.InternalMessageInfo

func (m *AccountProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SessionSubject struct {
	AuthenticatedAt      int64    `protobuf:"varint,1,opt,name=authenticated_at,json=authenticatedAt,proto3" json:"authenticated_at,omitempty"`
	ActivatedAt          int64    `protobuf:"varint,2,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionSubject) Reset()         { *m = SessionSubject{} }
func (m *SessionSubject) String() string { return proto.CompactTextString(m) }
func (*SessionSubject) ProtoMessage()    {}
func (*SessionSubject) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{1}
}

func (m *SessionSubject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionSubject.Unmarshal(m, b)
}
func (m *SessionSubject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionSubject.Marshal(b, m, deterministic)
}
func (m *SessionSubject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionSubject.Merge(m, src)
}
func (m *SessionSubject) XXX_Size() int {
	return xxx_messageInfo_SessionSubject.Size(m)
}
func (m *SessionSubject) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionSubject.DiscardUnknown(m)
}

var xxx_messageInfo_SessionSubject proto.InternalMessageInfo

func (m *SessionSubject) GetAuthenticatedAt() int64 {
	if m != nil {
		return m.AuthenticatedAt
	}
	return 0
}

func (m *SessionSubject) GetActivatedAt() int64 {
	if m != nil {
		return m.ActivatedAt
	}
	return 0
}

func (m *SessionSubject) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type SignInRequest struct {
	Identifier             string   `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Password               string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	UserAgent              string   `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	SourceIp               string   `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	ClientIp               string   `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ForwardedIps           []string `protobuf:"bytes,6,rep,name=forwarded_ips,json=forwardedIps,proto3" json:"forwarded_ips,omitempty"`
	SessionId              string   `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ActivationCodeDuration string   `protobuf:"bytes,8,opt,name=activation_code_duration,json=activationCodeDuration,proto3" json:"activation_code_duration,omitempty"`
	TenantId               string   `protobuf:"bytes,9,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *SignInRequest) Reset()         { *m = SignInRequest{} }
func (m *SignInRequest) String() string { return proto.CompactTextString(m) }
func (*SignInRequest) ProtoMessage()    {}
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{2}
}

func (m *SignInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInRequest.Unmarshal(m, b)
}
func (m *SignInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInRequest.Marshal(b, m, deterministic)
}
func (m *SignInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInRequest.Merge(m, src)
}
func (m *SignInRequest) XXX_Size() int {
	return xxx_messageInfo_SignInRequest.Size(m)
}
func (m *SignInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignInRequest proto.InternalMessageInfo

func (m *SignInRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *SignInRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignInRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *SignInRequest) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *SignInRequest) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *SignInRequest) GetForwardedIps() []string {
	if m != nil {
		return m.ForwardedIps
	}
	return nil
}

func (m *SignInRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SignInRequest) GetActivationCodeDuration() string {
	if m != nil {
		return m.ActivationCodeDuration
	}
	return ""
}

func (m *SignInRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type SignInResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActivationMethod     ActivationMethod           `protobuf:"varint,2,opt,name=activation_method,json=activationMethod,proto3,enum=sso.service.ActivationMethod" json:"activation_method,omitempty"`
	Subject              string                     `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Profile              *AccountProfile            `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SignInResponse) Reset()         { *m = SignInResponse{} }
func (m *SignInResponse) String() string { return proto.CompactTextString(m) }
func (*SignInResponse) ProtoMessage()    {}
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{3}
}

func (m *SignInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignInResponse.Unmarshal(m, b)
}
func (m *SignInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignInResponse.Marshal(b, m, deterministic)
}
func (m *SignInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignInResponse.Merge(m, src)
}
func (m *SignInResponse) XXX_Size() int {
	return xxx_messageInfo_SignInResponse.Size(m)
}
func (m *SignInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignInResponse proto.InternalMessageInfo

func (m *SignInResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SignInResponse) GetActivationMethod() ActivationMethod {
	if m != nil {
		return m.ActivationMethod
	}
	return ActivationMethod_NONE
}

func (m *SignInResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SignInResponse) GetProfile() *AccountProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type ActivateSessionRequest struct {
	ActivationCode       string   `protobuf:"bytes,1,opt,name=activation_code,json=activationCode,proto3" json:"activation_code,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	UserAgent            string   `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	SessionId            string   `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateSessionRequest) Reset()         { *m = ActivateSessionRequest{} }
func (m *ActivateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateSessionRequest) ProtoMessage()    {}
func (*ActivateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{4}
}

func (m *ActivateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateSessionRequest.Unmarshal(m, b)
}
func (m *ActivateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateSessionRequest.Marshal(b, m, deterministic)
}
func (m *ActivateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateSessionRequest.Merge(m, src)
}
func (m *ActivateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateSessionRequest.Size(m)
}
func (m *ActivateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateSessionRequest proto.InternalMessageInfo

func (m *ActivateSessionRequest) GetActivationCode() string {
	if m != nil {
		return m.ActivationCode
	}
	return ""
}

func (m *ActivateSessionRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *ActivateSessionRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *ActivateSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type ActivateSessionResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ActivateSessionResponse) Reset()         { *m = ActivateSessionResponse{} }
func (m *ActivateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*ActivateSessionResponse) ProtoMessage()    {}
func (*ActivateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{5}
}

func (m *ActivateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateSessionResponse.Unmarshal(m, b)
}
func (m *ActivateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateSessionResponse.Marshal(b, m, deterministic)
}
func (m *ActivateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateSessionResponse.Merge(m, src)
}
func (m *ActivateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_ActivateSessionResponse.Size(m)
}
func (m *ActivateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateSessionResponse proto.InternalMessageInfo

func (m *ActivateSessionResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RegisterEventRequest struct {
	Level                EventLevel        `protobuf:"varint,1,opt,name=level,proto3,enum=sso.service.EventLevel" json:"level,omitempty"`
	IsSensitive          bool              `protobuf:"varint,2,opt,name=is_sensitive,json=isSensitive,proto3" json:"is_sensitive,omitempty"`
	Message              string            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data                 map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RegisterEventRequest) Reset()         { *m = RegisterEventRequest{} }
func (m *RegisterEventRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterEventRequest) ProtoMessage()    {}
func (*RegisterEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{6}
}

func (m *RegisterEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEventRequest.Unmarshal(m, b)
}
func (m *RegisterEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEventRequest.Marshal(b, m, deterministic)
}
func (m *RegisterEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEventRequest.Merge(m, src)
}
func (m *RegisterEventRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterEventRequest.Size(m)
}
func (m *RegisterEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEventRequest proto.InternalMessageInfo

func (m *RegisterEventRequest) GetLevel() EventLevel {
	if m != nil {
		return m.Level
	}
	return EventLevel_INFO
}

func (m *RegisterEventRequest) GetIsSensitive() bool {
	if m != nil {
		return m.IsSensitive
	}
	return false
}

func (m *RegisterEventRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterEventRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterEventResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RegisterEventResponse) Reset()         { *m = RegisterEventResponse{} }
func (m *RegisterEventResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterEventResponse) ProtoMessage()    {}
func (*RegisterEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{7}
}

func (m *RegisterEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEventResponse.Unmarshal(m, b)
}
func (m *RegisterEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEventResponse.Marshal(b, m, deterministic)
}
func (m *RegisterEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEventResponse.Merge(m, src)
}
func (m *RegisterEventResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterEventResponse.Size(m)
}
func (m *RegisterEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEventResponse proto.InternalMessageInfo

func (m *RegisterEventResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RevokeScopesRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scopes               []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeScopesRequest) Reset()         { *m = RevokeScopesRequest{} }
func (m *RevokeScopesRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeScopesRequest) ProtoMessage()    {}
func (*RevokeScopesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{8}
}

func (m *RevokeScopesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeScopesRequest.Unmarshal(m, b)
}
func (m *RevokeScopesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeScopesRequest.Marshal(b, m, deterministic)
}
func (m *RevokeScopesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeScopesRequest.Merge(m, src)
}
func (m *RevokeScopesRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeScopesRequest.Size(m)
}
func (m *RevokeScopesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeScopesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeScopesRequest proto.InternalMessageInfo

func (m *RevokeScopesRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *RevokeScopesRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *RevokeScopesRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type RevokeScopesResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RevokeScopesResponse) Reset()         { *m = RevokeScopesResponse{} }
func (m *RevokeScopesResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeScopesResponse) ProtoMessage()    {}
func (*RevokeScopesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{9}
}

func (m *RevokeScopesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeScopesResponse.Unmarshal(m, b)
}
func (m *RevokeScopesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeScopesResponse.Marshal(b, m, deterministic)
}
func (m *RevokeScopesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeScopesResponse.Merge(m, src)
}
func (m *RevokeScopesResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeScopesResponse.Size(m)
}
func (m *RevokeScopesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeScopesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeScopesResponse proto.InternalMessageInfo

func (m *RevokeScopesResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type RevokeTokenRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeTokenRequest) Reset()         { *m = RevokeTokenRequest{} }
func (m *RevokeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenRequest) ProtoMessage()    {}
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{10}
}

func (m *RevokeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenRequest.Unmarshal(m, b)
}
func (m *RevokeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenRequest.Marshal(b, m, deterministic)
}
func (m *RevokeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenRequest.Merge(m, src)
}
func (m *RevokeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenRequest.Size(m)
}
func (m *RevokeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenRequest proto.InternalMessageInfo

func (m *RevokeTokenRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *RevokeTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type RevokeTokenResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RevokeTokenResponse) Reset()         { *m = RevokeTokenResponse{} }
func (m *RevokeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenResponse) ProtoMessage()    {}
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{11}
}

func (m *RevokeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenResponse.Unmarshal(m, b)
}
func (m *RevokeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenResponse.Marshal(b, m, deterministic)
}
func (m *RevokeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenResponse.Merge(m, src)
}
func (m *RevokeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenResponse.Size(m)
}
func (m *RevokeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenResponse proto.InternalMessageInfo

func (m *RevokeTokenResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type AuthorizeClientRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ResponseType         string   `protobuf:"bytes,3,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	RedirectUri          string   `protobuf:"bytes,4,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scopes               []string `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	State                string   `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	TenantId             string   `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizeClientRequest) Reset()         { *m = AuthorizeClientRequest{} }
func (m *AuthorizeClientRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizeClientRequest) ProtoMessage()    {}
func (*AuthorizeClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{12}
}

func (m *AuthorizeClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeClientRequest.Unmarshal(m, b)
}
func (m *AuthorizeClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeClientRequest.Marshal(b, m, deterministic)
}
func (m *AuthorizeClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeClientRequest.Merge(m, src)
}
func (m *AuthorizeClientRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorizeClientRequest.Size(m)
}
func (m *AuthorizeClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeClientRequest proto.InternalMessageInfo

func (m *AuthorizeClientRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthorizeClientRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AuthorizeClientRequest) GetResponseType() string {
	if m != nil {
		return m.ResponseType
	}
	return ""
}

func (m *AuthorizeClientRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *AuthorizeClientRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *AuthorizeClientRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthorizeClientRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type AuthorizeClientResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	UnauthorizedScopes   []string                   `protobuf:"bytes,2,rep,name=unauthorized_scopes,json=unauthorizedScopes,proto3" json:"unauthorized_scopes,omitempty"`
	ClientName           string                     `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AuthorizeClientResponse) Reset()         { *m = AuthorizeClientResponse{} }
func (m *AuthorizeClientResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizeClientResponse) ProtoMessage()    {}
func (*AuthorizeClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{13}
}

func (m *AuthorizeClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizeClientResponse.Unmarshal(m, b)
}
func (m *AuthorizeClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizeClientResponse.Marshal(b, m, deterministic)
}
func (m *AuthorizeClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizeClientResponse.Merge(m, src)
}
func (m *AuthorizeClientResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorizeClientResponse.Size(m)
}
func (m *AuthorizeClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizeClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizeClientResponse proto.InternalMessageInfo

func (m *AuthorizeClientResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AuthorizeClientResponse) GetUnauthorizedScopes() []string {
	if m != nil {
		return m.UnauthorizedScopes
	}
	return nil
}

func (m *AuthorizeClientResponse) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

type GrantScopesRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Scopes               []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	TenantId             string   `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrantScopesRequest) Reset()         { *m = GrantScopesRequest{} }
func (m *GrantScopesRequest) String() string { return proto.CompactTextString(m) }
func (*GrantScopesRequest) ProtoMessage()    {}
func (*GrantScopesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{14}
}

func (m *GrantScopesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantScopesRequest.Unmarshal(m, b)
}
func (m *GrantScopesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantScopesRequest.Marshal(b, m, deterministic)
}
func (m *GrantScopesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantScopesRequest.Merge(m, src)
}
func (m *GrantScopesRequest) XXX_Size() int {
	return xxx_messageInfo_GrantScopesRequest.Size(m)
}
func (m *GrantScopesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantScopesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GrantScopesRequest proto.InternalMessageInfo

func (m *GrantScopesRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GrantScopesRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *GrantScopesRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *GrantScopesRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

type GrantScopesResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GrantScopesResponse) Reset()         { *m = GrantScopesResponse{} }
func (m *GrantScopesResponse) String() string { return proto.CompactTextString(m) }
func (*GrantScopesResponse) ProtoMessage()    {}
func (*GrantScopesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{15}
}

func (m *GrantScopesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrantScopesResponse.Unmarshal(m, b)
}
func (m *GrantScopesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrantScopesResponse.Marshal(b, m, deterministic)
}
func (m *GrantScopesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrantScopesResponse.Merge(m, src)
}
func (m *GrantScopesResponse) XXX_Size() int {
	return xxx_messageInfo_GrantScopesResponse.Size(m)
}
func (m *GrantScopesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GrantScopesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GrantScopesResponse proto.InternalMessageInfo

func (m *GrantScopesResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type NewRefreshTokenRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Subject              string   `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	SessionId            string   `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AuthorizationCode    string   `protobuf:"bytes,4,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"`
	Duration             string   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	ForceNew             bool     `protobuf:"varint,6,opt,name=force_new,json=forceNew,proto3" json:"force_new,omitempty"`
	ClientSecret         string   `protobuf:"bytes,7,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	RedirectUri          string   `protobuf:"bytes,8,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scopes               []string `protobuf:"bytes,9,rep,name=scopes,proto3" json:"scopes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRefreshTokenRequest) Reset()         { *m = NewRefreshTokenRequest{} }
func (m *NewRefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*NewRefreshTokenRequest) ProtoMessage()    {}
func (*NewRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{16}
}

func (m *NewRefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRefreshTokenRequest.Unmarshal(m, b)
}
func (m *NewRefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *NewRefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRefreshTokenRequest.Merge(m, src)
}
func (m *NewRefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_NewRefreshTokenRequest.Size(m)
}
func (m *NewRefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewRefreshTokenRequest proto.InternalMessageInfo

func (m *NewRefreshTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetAuthorizationCode() string {
	if m != nil {
		return m.AuthorizationCode
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetForceNew() bool {
	if m != nil {
		return m.ForceNew
	}
	return false
}

func (m *NewRefreshTokenRequest) GetClientSecret() string {
	if m != nil {
		return m.ClientSecret
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *NewRefreshTokenRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

type NewRefreshTokenResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RefreshTokenId       string                     `protobuf:"bytes,2,opt,name=refresh_token_id,json=refreshTokenId,proto3" json:"refresh_token_id,omitempty"`
	ExpiresAt            int64                      `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NewRefreshTokenResponse) Reset()         { *m = NewRefreshTokenResponse{} }
func (m *NewRefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*NewRefreshTokenResponse) ProtoMessage()    {}
func (*NewRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{17}
}

func (m *NewRefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRefreshTokenResponse.Unmarshal(m, b)
}
func (m *NewRefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *NewRefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRefreshTokenResponse.Merge(m, src)
}
func (m *NewRefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_NewRefreshTokenResponse.Size(m)
}
func (m *NewRefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewRefreshTokenResponse proto.InternalMessageInfo

func (m *NewRefreshTokenResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NewRefreshTokenResponse) GetRefreshTokenId() string {
	if m != nil {
		return m.RefreshTokenId
	}
	return ""
}

func (m *NewRefreshTokenResponse) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type PurgeClientCacheRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeClientCacheRequest) Reset()         { *m = PurgeClientCacheRequest{} }
func (m *PurgeClientCacheRequest) String() string { return proto.CompactTextString(m) }
func (*PurgeClientCacheRequest) ProtoMessage()    {}
func (*PurgeClientCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{18}
}

func (m *PurgeClientCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeClientCacheRequest.Unmarshal(m, b)
}
func (m *PurgeClientCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeClientCacheRequest.Marshal(b, m, deterministic)
}
func (m *PurgeClientCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeClientCacheRequest.Merge(m, src)
}
func (m *PurgeClientCacheRequest) XXX_Size() int {
	return xxx_messageInfo_PurgeClientCacheRequest.Size(m)
}
func (m *PurgeClientCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeClientCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeClientCacheRequest proto.InternalMessageInfo

func (m *PurgeClientCacheRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

type PurgeClientCacheResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DeletedCount         int32                      `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PurgeClientCacheResponse) Reset()         { *m = PurgeClientCacheResponse{} }
func (m *PurgeClientCacheResponse) String() string { return proto.CompactTextString(m) }
func (*PurgeClientCacheResponse) ProtoMessage()    {}
func (*PurgeClientCacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{19}
}

func (m *PurgeClientCacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeClientCacheResponse.Unmarshal(m, b)
}
func (m *PurgeClientCacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeClientCacheResponse.Marshal(b, m, deterministic)
}
func (m *PurgeClientCacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeClientCacheResponse.Merge(m, src)
}
func (m *PurgeClientCacheResponse) XXX_Size() int {
	return xxx_messageInfo_PurgeClientCacheResponse.Size(m)
}
func (m *PurgeClientCacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeClientCacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeClientCacheResponse proto.InternalMessageInfo

func (m *PurgeClientCacheResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PurgeClientCacheResponse) GetDeletedCount() int32 {
	if m != nil {
		return m.DeletedCount
	}
	return 0
}

type PurgeAccountCacheRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	SessionId            string   `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurgeAccountCacheRequest) Reset()         { *m = PurgeAccountCacheRequest{} }
func (m *PurgeAccountCacheRequest) String() string { return proto.CompactTextString(m) }
func (*PurgeAccountCacheRequest) ProtoMessage()    {}
func (*PurgeAccountCacheRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{20}
}

func (m *PurgeAccountCacheRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeAccountCacheRequest.Unmarshal(m, b)
}
func (m *PurgeAccountCacheRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeAccountCacheRequest.Marshal(b, m, deterministic)
}
func (m *PurgeAccountCacheRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeAccountCacheRequest.Merge(m, src)
}
func (m *PurgeAccountCacheRequest) XXX_Size() int {
	return xxx_messageInfo_PurgeAccountCacheRequest.Size(m)
}
func (m *PurgeAccountCacheRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeAccountCacheRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeAccountCacheRequest proto.InternalMessageInfo

func (m *PurgeAccountCacheRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *PurgeAccountCacheRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type PurgeAccountCacheResponse struct {
	Status               *sso_common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DeletedCount         int32                      `protobuf:"varint,2,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PurgeAccountCacheResponse) Reset()         { *m = PurgeAccountCacheResponse{} }
func (m *PurgeAccountCacheResponse) String() string { return proto.CompactTextString(m) }
func (*PurgeAccountCacheResponse) ProtoMessage()    {}
func (*PurgeAccountCacheResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1cf8ce11efbd569b, []int{21}
}

func (m *PurgeAccountCacheResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurgeAccountCacheResponse.Unmarshal(m, b)
}
func (m *PurgeAccountCacheResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurgeAccountCacheResponse.Marshal(b, m, deterministic)
}
func (m *PurgeAccountCacheResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurgeAccountCacheResponse.Merge(m, src)
}
func (m *PurgeAccountCacheResponse) XXX_Size() int {
	return xxx_messageInfo_PurgeAccountCacheResponse.Size(m)
}
func (m *PurgeAccountCacheResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PurgeAccountCacheResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PurgeAccountCacheResponse proto.InternalMessageInfo

func (m *PurgeAccountCacheResponse) GetStatus() *sso_common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *PurgeAccountCacheResponse) GetDeletedCount() int32 {
	if m != nil {
		return m.DeletedCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("sso.service.ActivationMethod", ActivationMethod_name, ActivationMethod_value)
	proto.RegisterEnum("sso.service.EventLevel", EventLevel_name, EventLevel_value)
	proto.RegisterType((*AccountProfile)(nil), "sso.service.AccountProfile")
	proto.RegisterType((*SessionSubject)(nil), "sso.service.SessionSubject")
	proto.RegisterType((*SignInRequest)(nil), "sso.service.SignInRequest")
	proto.RegisterType((*SignInResponse)(nil), "sso.service.SignInResponse")
	proto.RegisterType((*ActivateSessionRequest)(nil), "sso.service.ActivateSessionRequest")
	proto.RegisterType((*ActivateSessionResponse)(nil), "sso.service.ActivateSessionResponse")
	proto.RegisterType((*RegisterEventRequest)(nil), "sso.service.RegisterEventRequest")
	proto.RegisterMapType((map[string]string)(nil), "sso.service.RegisterEventRequest.DataEntry")
	proto.RegisterType((*RegisterEventResponse)(nil), "sso.service.RegisterEventResponse")
	proto.RegisterType((*RevokeScopesRequest)(nil), "sso.service.RevokeScopesRequest")
	proto.RegisterType((*RevokeScopesResponse)(nil), "sso.service.RevokeScopesResponse")
	proto.RegisterType((*RevokeTokenRequest)(nil), "sso.service.RevokeTokenRequest")
	proto.RegisterType((*RevokeTokenResponse)(nil), "sso.service.RevokeTokenResponse")
	proto.RegisterType((*AuthorizeClientRequest)(nil), "sso.service.AuthorizeClientRequest")
	proto.RegisterType((*AuthorizeClientResponse)(nil), "sso.service.AuthorizeClientResponse")
	proto.RegisterType((*GrantScopesRequest)(nil), "sso.service.GrantScopesRequest")
	proto.RegisterType((*GrantScopesResponse)(nil), "sso.service.GrantScopesResponse")
	proto.RegisterType((*NewRefreshTokenRequest)(nil), "sso.service.NewRefreshTokenRequest")
	proto.RegisterType((*NewRefreshTokenResponse)(nil), "sso.service.NewRefreshTokenResponse")
	proto.RegisterType((*PurgeClientCacheRequest)(nil), "sso.service.PurgeClientCacheRequest")
	proto.RegisterType((*PurgeClientCacheResponse)(nil), "sso.service.PurgeClientCacheResponse")
	proto.RegisterType((*PurgeAccountCacheRequest)(nil), "sso.service.PurgeAccountCacheRequest")
	proto.RegisterType((*PurgeAccountCacheResponse)(nil), "sso.service.PurgeAccountCacheResponse")
}

func init() { proto.RegisterFile("sso-service/sso-service.proto", fileDescriptor_1cf8ce11efbd569b) }

var fileDescriptor_1cf8ce11efbd569b = []byte{
	// 1387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xef, 0xf9, 0x4f, 0x62, 0x8f, 0x1d, 0xe7, 0xba, 0x0d, 0x89, 0x71, 0x54, 0x9a, 0x3a, 0x05,
	0x42, 0x51, 0x62, 0x61, 0x04, 0x54, 0xbc, 0xa0, 0x6b, 0x6a, 0x52, 0xb7, 0x8d, 0x1d, 0x9d, 0x53,
	0x2a, 0xa1, 0x4a, 0xd6, 0xe5, 0x6e, 0xe2, 0x1c, 0xb1, 0xef, 0x8e, 0xdb, 0x3d, 0x87, 0x20, 0x21,
	0xf1, 0x29, 0x90, 0x78, 0xe2, 0x85, 0x0f, 0xc0, 0x13, 0xaf, 0x7c, 0x0a, 0x3e, 0x00, 0x7c, 0x0e,
	0x1e, 0xd0, 0xee, 0xed, 0x39, 0x77, 0x67, 0x3b, 0x41, 0xb5, 0x78, 0xbb, 0x9d, 0x9d, 0x9d, 0x99,
	0xfd, 0xcd, 0x6f, 0x67, 0xc6, 0x86, 0xbb, 0x94, 0xba, 0xbb, 0x14, 0xfd, 0xb1, 0x6d, 0x62, 0x23,
	0xf6, 0xbd, 0xe7, 0xf9, 0x2e, 0x73, 0x49, 0x89, 0x52, 0x77, 0x4f, 0x8a, 0x6a, 0x9b, 0x7c, 0xdf,
	0x74, 0x47, 0x23, 0xd7, 0x69, 0x5c, 0x7d, 0x86, 0x9a, 0xf5, 0x07, 0x50, 0xd1, 0x4c, 0xd3, 0x0d,
	0x1c, 0x76, 0xe4, 0xbb, 0xa7, 0xf6, 0x10, 0x09, 0x81, 0x9c, 0x63, 0x8c, 0xb0, 0xaa, 0x6c, 0x29,
	0x3b, 0x45, 0x5d, 0x7c, 0xd7, 0x7f, 0x80, 0x4a, 0x0f, 0x29, 0xb5, 0x5d, 0xa7, 0x17, 0x9c, 0x7c,
	0x83, 0x26, 0x23, 0x1f, 0x80, 0x6a, 0x04, 0xec, 0x0c, 0x1d, 0x66, 0x9b, 0x06, 0x43, 0xab, 0x6f,
	0x30, 0x71, 0x22, 0xab, 0xaf, 0x26, 0xe4, 0x1a, 0x23, 0xf7, 0xa1, 0x6c, 0x98, 0xcc, 0x1e, 0x47,
	0x6a, 0x19, 0xa1, 0x56, 0x9a, 0xc8, 0x34, 0x46, 0xee, 0x02, 0xe0, 0x77, 0x9e, 0xed, 0x23, 0xe5,
	0x0a, 0x59, 0xa1, 0x50, 0x94, 0x12, 0x8d, 0xd5, 0xff, 0xc8, 0xc0, 0x4a, 0xcf, 0x1e, 0x38, 0x6d,
	0x47, 0xc7, 0x6f, 0x03, 0xa4, 0x8c, 0xbc, 0x03, 0x60, 0x5b, 0xdc, 0xc9, 0xa9, 0x8d, 0xbe, 0x0c,
	0x35, 0x26, 0x21, 0x35, 0x28, 0x78, 0x06, 0xa5, 0x17, 0xae, 0x6f, 0x09, 0x7f, 0x45, 0x7d, 0xb2,
	0xe6, 0xce, 0x02, 0x8a, 0x7e, 0xdf, 0x18, 0xa0, 0x13, 0x3a, 0x2b, 0xea, 0x45, 0x2e, 0xd1, 0xb8,
	0x80, 0x6c, 0x42, 0x91, 0xba, 0x81, 0x6f, 0x62, 0xdf, 0xf6, 0xaa, 0xb9, 0xf0, 0x6c, 0x28, 0x68,
	0x7b, 0x7c, 0xd3, 0x1c, 0xda, 0xe8, 0x30, 0xbe, 0x99, 0x0f, 0x37, 0x43, 0x41, 0xdb, 0x23, 0xdb,
	0xb0, 0x72, 0xea, 0xfa, 0x17, 0x86, 0x6f, 0xa1, 0xd5, 0xb7, 0x3d, 0x5a, 0x5d, 0xda, 0xca, 0xee,
	0x14, 0xf5, 0xf2, 0x44, 0xd8, 0xf6, 0x28, 0xf7, 0x4e, 0x43, 0x28, 0xfb, 0xb6, 0x55, 0x5d, 0x0e,
	0xbd, 0x4b, 0x49, 0xdb, 0x22, 0x8f, 0xa0, 0x2a, 0x81, 0xe1, 0x1a, 0xa6, 0x6b, 0x61, 0xdf, 0x0a,
	0x7c, 0xb1, 0xaa, 0x16, 0x84, 0xf2, 0xfa, 0xd5, 0xfe, 0xbe, 0x6b, 0xe1, 0x13, 0xb9, 0xcb, 0x43,
	0x63, 0xe8, 0x18, 0x3c, 0x34, 0xab, 0x5a, 0x0c, 0x43, 0x0b, 0x05, 0x6d, 0xab, 0xfe, 0x97, 0x02,
	0x95, 0x08, 0x41, 0xea, 0xb9, 0x0e, 0x45, 0xd2, 0x84, 0x25, 0xca, 0x0c, 0x16, 0x50, 0x01, 0x5f,
	0xa9, 0x59, 0xdb, 0xe3, 0xa4, 0x91, 0xe4, 0x88, 0xb4, 0x7a, 0x42, 0x43, 0x97, 0x9a, 0xe4, 0x19,
	0xdc, 0x8e, 0x45, 0x37, 0x42, 0x76, 0xe6, 0x86, 0xf8, 0x56, 0x9a, 0x77, 0xf7, 0x62, 0x9c, 0xdb,
	0xd3, 0x26, 0x5a, 0x87, 0x42, 0x49, 0x57, 0x8d, 0x94, 0x84, 0x54, 0x61, 0x99, 0x86, 0x64, 0x92,
	0x39, 0x88, 0x96, 0xe4, 0x13, 0x58, 0xf6, 0x42, 0x32, 0x0a, 0xfc, 0x4b, 0xcd, 0xcd, 0x94, 0xed,
	0x38, 0x5f, 0xf5, 0x48, 0xb7, 0xfe, 0xb3, 0x02, 0xeb, 0xd2, 0x2f, 0x4a, 0xb6, 0x46, 0x74, 0x79,
	0x1f, 0x56, 0x53, 0xa8, 0x4a, 0xce, 0x54, 0x92, 0x60, 0xc6, 0x83, 0xca, 0x24, 0x83, 0xba, 0x81,
	0x35, 0xc9, 0xb4, 0xe6, 0x52, 0x69, 0xad, 0x1f, 0xc2, 0xc6, 0x54, 0x68, 0x6f, 0x9e, 0x87, 0xfa,
	0x3f, 0x0a, 0xac, 0xe9, 0x38, 0xb0, 0x29, 0x43, 0xbf, 0x35, 0x46, 0x87, 0x45, 0x17, 0xdd, 0x85,
	0xfc, 0x10, 0xc7, 0x38, 0x14, 0xb6, 0x2a, 0xcd, 0x8d, 0x04, 0x70, 0x42, 0xf3, 0x05, 0xdf, 0xd6,
	0x43, 0x2d, 0xfe, 0x34, 0x6d, 0xda, 0xa7, 0xe8, 0x50, 0x9b, 0xd9, 0x63, 0x14, 0x77, 0x2e, 0xe8,
	0x25, 0x9b, 0xf6, 0x22, 0x11, 0x47, 0x64, 0x84, 0x94, 0x1a, 0x03, 0x8c, 0xd2, 0x24, 0x97, 0xe4,
	0x0b, 0xc8, 0x59, 0x06, 0x33, 0xaa, 0xb9, 0xad, 0xec, 0x4e, 0xa9, 0xf9, 0x61, 0xc2, 0xd5, 0xac,
	0xe0, 0xf6, 0x9e, 0x18, 0xcc, 0x68, 0x39, 0xcc, 0xbf, 0xd4, 0xc5, 0xc1, 0xda, 0x67, 0x50, 0x9c,
	0x88, 0x88, 0x0a, 0xd9, 0x73, 0xbc, 0x94, 0x69, 0xe1, 0x9f, 0x64, 0x0d, 0xf2, 0x63, 0x63, 0x18,
	0xa0, 0xcc, 0x44, 0xb8, 0xf8, 0x3c, 0xf3, 0x48, 0xa9, 0x3f, 0x87, 0xb7, 0x52, 0x0e, 0x16, 0xc0,
	0xd2, 0x82, 0x3b, 0x3a, 0x8e, 0xdd, 0x73, 0xec, 0x99, 0xae, 0x87, 0x34, 0x42, 0x32, 0xc6, 0x04,
	0x25, 0xc9, 0x84, 0x58, 0x0d, 0x98, 0x14, 0x17, 0x59, 0x03, 0x2c, 0xb2, 0x0e, 0x4b, 0x54, 0xd8,
	0xa9, 0x66, 0xc5, 0xe3, 0x97, 0xab, 0xfa, 0x33, 0x9e, 0xb0, 0xb8, 0x97, 0x05, 0x22, 0x7e, 0x0e,
	0x24, 0xb4, 0x75, 0xec, 0x9e, 0xa3, 0xb3, 0x58, 0xc0, 0xf5, 0x76, 0x74, 0x7d, 0x69, 0x6c, 0x81,
	0xb8, 0xfe, 0xe6, 0x0f, 0x30, 0x60, 0x67, 0xae, 0x6f, 0x7f, 0x8f, 0xfb, 0xc2, 0xc1, 0x82, 0x68,
	0x6e, 0xc3, 0x8a, 0x2f, 0x7d, 0xf5, 0xd9, 0xa5, 0x17, 0x51, 0xb0, 0x1c, 0x09, 0x8f, 0x2f, 0x3d,
	0xe4, 0x24, 0xf6, 0xd1, 0xb2, 0x7d, 0x34, 0x59, 0x3f, 0xf0, 0x6d, 0xf9, 0xf8, 0x4a, 0x91, 0xec,
	0xa5, 0x6f, 0xc7, 0xb2, 0x92, 0x8f, 0x67, 0x85, 0x53, 0x8c, 0xc7, 0x8e, 0xd5, 0xa5, 0x90, 0x62,
	0x62, 0x91, 0xac, 0xa4, 0xcb, 0xa9, 0x4a, 0xfa, 0x8b, 0x02, 0x1b, 0x53, 0x97, 0x5c, 0xa0, 0xa4,
	0x36, 0xe0, 0x4e, 0xe0, 0x18, 0x91, 0x41, 0xab, 0x2f, 0xe3, 0xcc, 0x88, 0x38, 0x49, 0x7c, 0x2b,
	0x64, 0x0e, 0xb9, 0x07, 0x25, 0x09, 0x98, 0x68, 0xd3, 0x21, 0x22, 0x10, 0x8a, 0x3a, 0xbc, 0x59,
	0xff, 0xa8, 0x00, 0x39, 0xf0, 0x0d, 0x87, 0x25, 0x09, 0x9d, 0x00, 0x5a, 0x49, 0x01, 0x3d, 0xbf,
	0xee, 0xcd, 0x21, 0x74, 0x12, 0xa4, 0x5c, 0x0a, 0xa4, 0x36, 0xdc, 0x49, 0x44, 0xb0, 0x00, 0xa9,
	0x7e, 0xcf, 0xc0, 0x7a, 0x07, 0x2f, 0x74, 0x3c, 0xf5, 0x91, 0x9e, 0x25, 0x18, 0xff, 0x86, 0x37,
	0x4a, 0x96, 0xea, 0x6c, 0xba, 0x03, 0xef, 0x02, 0x89, 0x30, 0x8f, 0xb5, 0x8b, 0xf0, 0x86, 0xb7,
	0x13, 0x3b, 0xa2, 0x63, 0xd4, 0xa0, 0x30, 0x69, 0xd0, 0x72, 0x20, 0xb0, 0x62, 0x2d, 0xf9, 0xd4,
	0xe5, 0x93, 0x84, 0x83, 0x17, 0x82, 0x62, 0x05, 0xbd, 0x20, 0x04, 0x1d, 0xbc, 0xe0, 0xdc, 0x96,
	0xd1, 0x53, 0x34, 0x7d, 0x64, 0x92, 0x69, 0xe5, 0x50, 0xd8, 0x13, 0xb2, 0x29, 0x6e, 0x17, 0xae,
	0xe3, 0x76, 0x31, 0x51, 0x71, 0x7e, 0x52, 0x60, 0x63, 0x0a, 0xb8, 0x05, 0x88, 0xba, 0x03, 0xaa,
	0x1f, 0xda, 0xea, 0x33, 0x6e, 0xec, 0xea, 0xbd, 0x56, 0xfc, 0x98, 0x8f, 0xb6, 0x75, 0xd3, 0x34,
	0xf7, 0x29, 0x6c, 0x1c, 0x05, 0xfe, 0x40, 0x3e, 0x9e, 0x7d, 0xc3, 0x3c, 0xc3, 0xff, 0x92, 0xd1,
	0x3a, 0x85, 0xea, 0xf4, 0xb9, 0x05, 0x2e, 0xb4, 0x0d, 0x2b, 0x16, 0x0e, 0x91, 0x4f, 0xa5, 0x62,
	0xa0, 0x10, 0xb7, 0xc9, 0xeb, 0x65, 0x29, 0xdc, 0xe7, 0xb2, 0x7a, 0x4f, 0x3a, 0x95, 0x43, 0x47,
	0x22, 0xda, 0xf9, 0x45, 0x2d, 0x49, 0xb1, 0x4c, 0x7a, 0x1a, 0x60, 0xf0, 0xf6, 0x0c, 0xa3, 0xff,
	0xf3, 0x55, 0x1e, 0x22, 0xa8, 0xe9, 0xb1, 0x8c, 0x14, 0x20, 0xd7, 0xe9, 0x76, 0x5a, 0xea, 0x2d,
	0x52, 0x84, 0x7c, 0xeb, 0x50, 0x6b, 0xbf, 0x50, 0x15, 0xb2, 0x0c, 0xd9, 0xde, 0x61, 0x4f, 0xcd,
	0x90, 0x2a, 0xac, 0x1d, 0x74, 0xbb, 0x07, 0x2f, 0x5a, 0x7d, 0xed, 0xe5, 0xf1, 0xd3, 0x56, 0xe7,
	0xb8, 0xbd, 0xaf, 0x1d, 0x77, 0x75, 0x35, 0x4b, 0x4a, 0xb0, 0xfc, 0xaa, 0xf5, 0xf8, 0x69, 0xb7,
	0xfb, 0x5c, 0xcd, 0x91, 0x32, 0x14, 0x5e, 0x3d, 0xd5, 0x8e, 0x7b, 0xda, 0xd1, 0x91, 0x9a, 0x7f,
	0xb8, 0x0d, 0x70, 0x35, 0x68, 0x70, 0x07, 0xed, 0xce, 0x97, 0x5d, 0xf5, 0x96, 0x38, 0xa2, 0xe9,
	0x9d, 0x76, 0xe7, 0x40, 0x55, 0x9a, 0xbf, 0x65, 0x27, 0xbf, 0x3b, 0x7a, 0xe1, 0xc8, 0x40, 0x34,
	0x58, 0x0a, 0x27, 0x54, 0x52, 0x4b, 0x8c, 0x12, 0x89, 0xc1, 0xbf, 0xb6, 0x39, 0x73, 0x4f, 0x42,
	0xf7, 0x1a, 0x56, 0x53, 0x53, 0x16, 0xd9, 0x9e, 0x35, 0x96, 0xa6, 0xc6, 0xc3, 0xda, 0x83, 0xeb,
	0x95, 0xa4, 0xf5, 0xaf, 0x60, 0x25, 0x31, 0x75, 0x90, 0xfb, 0x37, 0x8e, 0x3c, 0xb5, 0xfa, 0x75,
	0x2a, 0xd2, 0x6e, 0x0f, 0xca, 0xf1, 0xd1, 0x80, 0x6c, 0xa5, 0xce, 0x4c, 0xcd, 0x26, 0xb5, 0xfb,
	0xd7, 0x68, 0x48, 0xa3, 0x47, 0x50, 0x8a, 0xb5, 0x75, 0x72, 0x6f, 0xc6, 0x89, 0x78, 0x2d, 0xad,
	0x6d, 0xcd, 0x57, 0x08, 0x2d, 0x36, 0x7f, 0xcd, 0xc0, 0x9a, 0x16, 0x2f, 0x7f, 0x51, 0xe2, 0x38,
	0xea, 0xc9, 0x86, 0x98, 0x46, 0x7d, 0xe6, 0x4c, 0x90, 0x46, 0x7d, 0x4e, 0x4f, 0x3d, 0x82, 0x52,
	0xac, 0x95, 0xa4, 0x2e, 0x32, 0xdd, 0xe6, 0x52, 0x17, 0x99, 0xd5, 0x85, 0x5e, 0xc3, 0x6a, 0xaa,
	0x2e, 0xa6, 0xe2, 0x9d, 0xdd, 0x6e, 0x52, 0xf1, 0xce, 0x29, 0xad, 0xcd, 0x3f, 0x95, 0xab, 0xdf,
	0xca, 0x12, 0xa0, 0x3e, 0xa8, 0xe9, 0xc2, 0x45, 0x92, 0xc6, 0xe6, 0xd4, 0xc3, 0xda, 0xbb, 0x37,
	0x68, 0xc9, 0x1b, 0x9d, 0xc0, 0xed, 0xa9, 0x7a, 0x42, 0x66, 0x9c, 0x9d, 0x51, 0xc4, 0x6a, 0xef,
	0xdd, 0xa4, 0x16, 0xfa, 0x78, 0xfc, 0xd1, 0xd7, 0x8d, 0x81, 0xcd, 0xce, 0x82, 0x13, 0x5e, 0x8a,
	0x1a, 0x03, 0x63, 0x64, 0xb8, 0x1e, 0x6d, 0x8c, 0x5c, 0xc7, 0xdd, 0xa5, 0xd4, 0x6d, 0x78, 0xe7,
	0x83, 0x86, 0x6d, 0x0d, 0xe3, 0xff, 0x45, 0x9c, 0x2c, 0x89, 0xbf, 0x18, 0x3e, 0xfe, 0x37, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0x37, 0x42, 0xe4, 0xad, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	ActivateSession(ctx context.Context, in *ActivateSessionRequest, opts ...grpc.CallOption) (*ActivateSessionResponse, error)
	RegisterEvent(ctx context.Context, in *RegisterEventRequest, opts ...grpc.CallOption) (*RegisterEventResponse, error)
	RevokeScopes(ctx context.Context, in *RevokeScopesRequest, opts ...grpc.CallOption) (*RevokeScopesResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AccountService/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ActivateSession(ctx context.Context, in *ActivateSessionRequest, opts ...grpc.CallOption) (*ActivateSessionResponse, error) {
	out := new(ActivateSessionResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AccountService/ActivateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RegisterEvent(ctx context.Context, in *RegisterEventRequest, opts ...grpc.CallOption) (*RegisterEventResponse, error) {
	out := new(RegisterEventResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AccountService/RegisterEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RevokeScopes(ctx context.Context, in *RevokeScopesRequest, opts ...grpc.CallOption) (*RevokeScopesResponse, error) {
	out := new(RevokeScopesResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AccountService/RevokeScopes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AccountService/RevokeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	ActivateSession(context.Context, *ActivateSessionRequest) (*ActivateSessionResponse, error)
	RegisterEvent(context.Context, *RegisterEventRequest) (*RegisterEventResponse, error)
	RevokeScopes(context.Context, *RevokeScopesRequest) (*RevokeScopesResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
}

// UnimplementedAccountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (*UnimplementedAccountServiceServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedAccountServiceServer) ActivateSession(ctx context.Context, req *ActivateSessionRequest) (*ActivateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateSession not implemented")
}
func (*UnimplementedAccountServiceServer) RegisterEvent(ctx context.Context, req *RegisterEventRequest) (*RegisterEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEvent not implemented")
}
func (*UnimplementedAccountServiceServer) RevokeScopes(ctx context.Context, req *RevokeScopesRequest) (*RevokeScopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeScopes not implemented")
}
func (*UnimplementedAccountServiceServer) RevokeToken(ctx context.Context, req *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AccountService/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ActivateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ActivateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AccountService/ActivateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ActivateSession(ctx, req.(*ActivateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RegisterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RegisterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AccountService/RegisterEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RegisterEvent(ctx, req.(*RegisterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RevokeScopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RevokeScopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AccountService/RevokeScopes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RevokeScopes(ctx, req.(*RevokeScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AccountService/RevokeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.service.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignIn",
			Handler:    _AccountService_SignIn_Handler,
		},
		{
			MethodName: "ActivateSession",
			Handler:    _AccountService_ActivateSession_Handler,
		},
		{
			MethodName: "RegisterEvent",
			Handler:    _AccountService_RegisterEvent_Handler,
		},
		{
			MethodName: "RevokeScopes",
			Handler:    _AccountService_RevokeScopes_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _AccountService_RevokeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-service/sso-service.proto",
}

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizationServiceClient interface {
	AuthorizeClient(ctx context.Context, in *AuthorizeClientRequest, opts ...grpc.CallOption) (*AuthorizeClientResponse, error)
	GrantScopes(ctx context.Context, in *GrantScopesRequest, opts ...grpc.CallOption) (*GrantScopesResponse, error)
	NewRefreshToken(ctx context.Context, in *NewRefreshTokenRequest, opts ...grpc.CallOption) (*NewRefreshTokenResponse, error)
}

type authorizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationServiceClient(cc *grpc.ClientConn) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) AuthorizeClient(ctx context.Context, in *AuthorizeClientRequest, opts ...grpc.CallOption) (*AuthorizeClientResponse, error) {
	out := new(AuthorizeClientResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AuthorizationService/AuthorizeClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) GrantScopes(ctx context.Context, in *GrantScopesRequest, opts ...grpc.CallOption) (*GrantScopesResponse, error) {
	out := new(GrantScopesResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AuthorizationService/GrantScopes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) NewRefreshToken(ctx context.Context, in *NewRefreshTokenRequest, opts ...grpc.CallOption) (*NewRefreshTokenResponse, error) {
	out := new(NewRefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/sso.service.AuthorizationService/NewRefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
type AuthorizationServiceServer interface {
	AuthorizeClient(context.Context, *AuthorizeClientRequest) (*AuthorizeClientResponse, error)
	GrantScopes(context.Context, *GrantScopesRequest) (*GrantScopesResponse, error)
	NewRefreshToken(context.Context, *NewRefreshTokenRequest) (*NewRefreshTokenResponse, error)
}

// UnimplementedAuthorizationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServiceServer struct {
}

func (*UnimplementedAuthorizationServiceServer) AuthorizeClient(ctx context.Context, req *AuthorizeClientRequest) (*AuthorizeClientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeClient not implemented")
}
func (*UnimplementedAuthorizationServiceServer) GrantScopes(ctx context.Context, req *GrantScopesRequest) (*GrantScopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantScopes not implemented")
}
func (*UnimplementedAuthorizationServiceServer) NewRefreshToken(ctx context.Context, req *NewRefreshTokenRequest) (*NewRefreshTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewRefreshToken not implemented")
}

func RegisterAuthorizationServiceServer(s *grpc.Server, srv AuthorizationServiceServer) {
	s.RegisterService(&_AuthorizationService_serviceDesc, srv)
}

func _AuthorizationService_AuthorizeClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).AuthorizeClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AuthorizationService/AuthorizeClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).AuthorizeClient(ctx, req.(*AuthorizeClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_GrantScopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).GrantScopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AuthorizationService/GrantScopes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).GrantScopes(ctx, req.(*GrantScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_NewRefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).NewRefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.AuthorizationService/NewRefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).NewRefreshToken(ctx, req.(*NewRefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.service.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizeClient",
			Handler:    _AuthorizationService_AuthorizeClient_Handler,
		},
		{
			MethodName: "GrantScopes",
			Handler:    _AuthorizationService_GrantScopes_Handler,
		},
		{
			MethodName: "NewRefreshToken",
			Handler:    _AuthorizationService_NewRefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-service/sso-service.proto",
}

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionServiceClient interface {
	PurgeClientCache(ctx context.Context, in *PurgeClientCacheRequest, opts ...grpc.CallOption) (*PurgeClientCacheResponse, error)
	PurgeAccountCache(ctx context.Context, in *PurgeAccountCacheRequest, opts ...grpc.CallOption) (*PurgeAccountCacheResponse, error)
}

type sessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) PurgeClientCache(ctx context.Context, in *PurgeClientCacheRequest, opts ...grpc.CallOption) (*PurgeClientCacheResponse, error) {
	out := new(PurgeClientCacheResponse)
	err := c.cc.Invoke(ctx, "/sso.service.SessionService/PurgeClientCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionServiceClient) PurgeAccountCache(ctx context.Context, in *PurgeAccountCacheRequest, opts ...grpc.CallOption) (*PurgeAccountCacheResponse, error) {
	out := new(PurgeAccountCacheResponse)
	err := c.cc.Invoke(ctx, "/sso.service.SessionService/PurgeAccountCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
type SessionServiceServer interface {
	PurgeClientCache(context.Context, *PurgeClientCacheRequest) (*PurgeClientCacheResponse, error)
	PurgeAccountCache(context.Context, *PurgeAccountCacheRequest) (*PurgeAccountCacheResponse, error)
}

// UnimplementedSessionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSessionServiceServer struct {
}

func (*UnimplementedSessionServiceServer) PurgeClientCache(ctx context.Context, req *PurgeClientCacheRequest) (*PurgeClientCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeClientCache not implemented")
}
func (*UnimplementedSessionServiceServer) PurgeAccountCache(ctx context.Context, req *PurgeAccountCacheRequest) (*PurgeAccountCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeAccountCache not implemented")
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_PurgeClientCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeClientCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).PurgeClientCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.SessionService/PurgeClientCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).PurgeClientCache(ctx, req.(*PurgeClientCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionService_PurgeAccountCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeAccountCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).PurgeAccountCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sso.service.SessionService/PurgeAccountCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).PurgeAccountCache(ctx, req.(*PurgeAccountCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sso.service.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurgeClientCache",
			Handler:    _SessionService_PurgeClientCache_Handler,
		},
		{
			MethodName: "PurgeAccountCache",
			Handler:    _SessionService_PurgeAccountCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sso-service/sso-service.proto",
}
